name: Build

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env: 
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goaaats.github.io/ffxiv/tools/launcher/addons/Hooks/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\"    
    - name: Run actions/checkout@v2 (FFXIVClientStructs)
      uses: actions/checkout@v2
      with:
        repository: daemitus/FFXIVClientStructs
        path: lib\FFXIVClientStructs
    - name: Build
      run: |
        dotnet restore -r win WondrousTailsSolver.sln
        dotnet build --configuration Release
    - uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: WondrousTailsSolver\bin\Release\WondrousTailsSolver
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: daemitus/MyDalamudPlugins
        token: ${{ secrets.PAT }}
    - uses: actions/download-artifact@v2
      with:
        name: PluginRepoZip
        path: plugins/WondrousTailsSolver
    - uses: EndBug/add-and-commit@v7
      with:
        add: --all
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update WondrousTailsSolver